# Generated by Django 2.2.7 on 2019-11-07 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SF_Details',
            fields=[
                ('id', models.CharField(primary_key=True,serialize=False, verbose_name='ID')),
                ('Salesforce_Edition', models.CharField(max_length=30)),
                ('Salesforce_Org_ID', models.CharField(max_length=50)),
                ('Salesforce_Org_Name', models.CharField(max_length=60)),
                ('Connected_by_User_Name', models.CharField(max_length=70)),
                ('Access_Token', models.CharField(max_length=70)),
                ('Refresh_Token', models.CharField(max_length=80)),
            ],
        ),
    ]
