# Generated by Django 2.2.7 on 2019-11-07 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sf_details',
            name='Access_Token',
            field=models.CharField(max_length=130),
        ),
        migrations.AlterField(
            model_name='sf_details',
            name='Refresh_Token',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sf_details',
            name='id',
            field=models.CharField( primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
