# Generated by Django 2.2.7 on 2019-11-07 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20191107_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sf_details',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
